package pe.edu.uni.ventapasajes.view;

import javax.swing.JInternalFrame;
import pe.edu.uni.ventapasajes.model.UsuarioModel;
import pe.edu.uni.ventapasajes.util.Session;

/**
 *
 * @author Gustavo Coronel
 */
public class MainView extends javax.swing.JFrame {

   /**
    * Creates new form MainView
    */
   public MainView() {
      initComponents();
      establecerTitulo();
      this.setExtendedState(MAXIMIZED_BOTH);
   }

   private void establecerTitulo() {
      UsuarioModel usuario = (UsuarioModel) Session.get("usuario");
      String titulo = "VENTA DE PASAJES";
      titulo += " [ Usuario: " + usuario.getUsuario() + " ] ";
      this.setTitle(titulo);
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      desktopPane = new javax.swing.JDesktopPane();
      menuBar = new javax.swing.JMenuBar();
      fileMenu = new javax.swing.JMenu();
      exitMenuItem = new javax.swing.JMenuItem();
      menuProcesos = new javax.swing.JMenu();
      menuProcesosCrearRuta = new javax.swing.JMenuItem();
      menuTablas = new javax.swing.JMenu();
      menuTablasClientes = new javax.swing.JMenuItem();
      menuTablasTripulacion = new javax.swing.JMenuItem();
      menuTablasEmpleado = new javax.swing.JMenuItem();
      menuConsultas = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      fileMenu.setMnemonic('f');
      fileMenu.setText("Archivo");

      exitMenuItem.setMnemonic('x');
      exitMenuItem.setText("Salir");
      exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            exitMenuItemActionPerformed(evt);
         }
      });
      fileMenu.add(exitMenuItem);

      menuBar.add(fileMenu);

      menuProcesos.setText("Procesos");

      menuProcesosCrearRuta.setText("Crear ruta");
      menuProcesosCrearRuta.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuProcesosCrearRutaActionPerformed(evt);
         }
      });
      menuProcesos.add(menuProcesosCrearRuta);

      menuBar.add(menuProcesos);

      menuTablas.setText("Tablas");

      menuTablasClientes.setText("Clientes");
      menuTablasClientes.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuTablasClientesActionPerformed(evt);
         }
      });
      menuTablas.add(menuTablasClientes);

      menuTablasTripulacion.setText("Tripulación");
      menuTablasTripulacion.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuTablasTripulacionActionPerformed(evt);
         }
      });
      menuTablas.add(menuTablasTripulacion);

      menuTablasEmpleado.setText("Empleado");
      menuTablasEmpleado.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuTablasEmpleadoActionPerformed(evt);
         }
      });
      menuTablas.add(menuTablasEmpleado);

      menuBar.add(menuTablas);

      menuConsultas.setText("Consultas");
      menuBar.add(menuConsultas);

      setJMenuBar(menuBar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
       System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

   private void menuTablasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasClientesActionPerformed
      mostrarForm(CrudClientesView.class);
   }//GEN-LAST:event_menuTablasClientesActionPerformed

   private void menuTablasTripulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasTripulacionActionPerformed
      mostrarForm(CrudTripulacionView.class);
   }//GEN-LAST:event_menuTablasTripulacionActionPerformed

   private void menuTablasEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasEmpleadoActionPerformed
      mostrarForm(CrudEmpleadoView.class);
   }//GEN-LAST:event_menuTablasEmpleadoActionPerformed

   private void menuProcesosCrearRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosCrearRutaActionPerformed
      mostrarForm(ProcCreaRutaView.class);
   }//GEN-LAST:event_menuProcesosCrearRutaActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new MainView().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JDesktopPane desktopPane;
   private javax.swing.JMenuItem exitMenuItem;
   private javax.swing.JMenu fileMenu;
   private javax.swing.JMenuBar menuBar;
   private javax.swing.JMenu menuConsultas;
   private javax.swing.JMenu menuProcesos;
   private javax.swing.JMenuItem menuProcesosCrearRuta;
   private javax.swing.JMenu menuTablas;
   private javax.swing.JMenuItem menuTablasClientes;
   private javax.swing.JMenuItem menuTablasEmpleado;
   private javax.swing.JMenuItem menuTablasTripulacion;
   // End of variables declaration//GEN-END:variables

   private void mostrarForm(Class<?> aClass) {
      try {
         // Variable de control
         JInternalFrame view = null;
         // Buscar instancia
         for (JInternalFrame form : desktopPane.getAllFrames()) {
            if (aClass.isInstance(form)) {
               view = form;
               break;
            }
         }
         // Crear instancia
         if (view == null) {
            view = (JInternalFrame) aClass.getConstructor().newInstance();
            desktopPane.add(view);
            view.setVisible(true);
            view.setMaximum(true);
         }
         view.setSelected(true);
      } catch (Exception e) {
      }
   }
}
