package pe.edu.uni.ventapasajes.view;

import pe.edu.uni.autoventas.util.UtilView;
import pe.edu.uni.ventapasajes.controller.ConsultaController;
import pe.edu.uni.ventapasajes.controller.SistemaController;
import pe.edu.uni.ventapasajes.model.ComboModel;
import pe.edu.uni.ventapasajes.model.RutaModel;
import pe.edu.uni.ventapasajes.model.UsuarioModel;
import pe.edu.uni.ventapasajes.util.Mensaje;
import pe.edu.uni.ventapasajes.util.Session;

/**
 *
 * @author Gustavo Coronel
 */
public class ProcCreaRutaView extends javax.swing.JInternalFrame {

   private final SistemaController sistemaController;
   private final ConsultaController consultaController;

   /**
    * Creates new form CrudClientesView
    */
   public ProcCreaRutaView() {
      initComponents();
      sistemaController = new SistemaController();
      consultaController = new ConsultaController();
      cargaComboOrigen();
      establecerNombre();
   }

   private void cargaComboOrigen() {
      UtilView.llenarCombo(cboOrigen, consultaController.leerCiudades());
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      btnProcesar = new javax.swing.JButton();
      btnSalir = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      txtNombre = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      txtDuracion = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      txtPrecio1 = new javax.swing.JTextField();
      txtPrecio2 = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      txtPrecio3 = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      cboOrigen = new javax.swing.JComboBox<>();
      cboDestino = new javax.swing.JComboBox<>();

      setClosable(true);
      setMaximizable(true);
      setResizable(true);
      setTitle("CREACION DE NUEVAS RUTAS");

      jPanel1.setBackground(new java.awt.Color(204, 204, 204));
      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(0, 153, 255))); // NOI18N

      btnProcesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/uni/ventapasajes/imagenes/aceptar.png"))); // NOI18N
      btnProcesar.setText("Procesar");
      btnProcesar.setToolTipText("Buscar empleados");
      btnProcesar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnProcesarActionPerformed(evt);
         }
      });

      btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/uni/ventapasajes/imagenes/cerrar.png"))); // NOI18N
      btnSalir.setText("Cancelar");
      btnSalir.setToolTipText("Cerrar ventana");
      btnSalir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSalirActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(btnProcesar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
               .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Nueva Ruta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(0, 153, 255))); // NOI18N

      jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel1.setText("Nombre");

      txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel2.setText("Origen");

      jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel3.setText("Destino");

      txtDuracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel4.setText("Duración");

      jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel5.setText("Precio 1");

      txtPrecio1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      txtPrecio2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel6.setText("Precio 2");

      txtPrecio3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel7.setText("Precio 3");

      cboOrigen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      cboOrigen.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cboOrigenActionPerformed(evt);
         }
      });

      cboDestino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      cboDestino.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cboDestinoActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cboOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cboDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtPrecio3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(181, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(cboOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(cboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtPrecio3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(20, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
      try {
         // Combos
         ComboModel origen = (ComboModel) cboOrigen.getSelectedItem();
         ComboModel destino = (ComboModel) cboDestino.getSelectedItem();
         // Datos del formulario
         RutaModel model = new RutaModel();
         model.setNombre(txtNombre.getText());
         model.setOrigen(origen.getId());
         model.setDestino(destino.getId());
         model.setDuracion(txtDuracion.getText());
         model.setPrecio1(Double.valueOf(txtPrecio1.getText()));
         model.setPrecio2(Double.valueOf(txtPrecio2.getText()));
         model.setPrecio3(Double.valueOf(txtPrecio3.getText()));
         // Codigo del empleado
         UsuarioModel usuario = (UsuarioModel) Session.get("usuario");
         model.setEmpleado(usuario.getId());
         // Proceso
         sistemaController.creacionRuta(model);
         Mensaje.info(this, "Ruta creada con ID " + model.getId() + ".");
         // Limpiar los controles falta
         txtNombre.setText("");
         cboOrigen.setSelectedIndex(-1);
         cboDestino.removeAllItems();
         txtDuracion.setText("");
         txtPrecio1.setText("");
         txtPrecio2.setText("");
         txtPrecio3.setText("");
      } catch (Exception e) {
         Mensaje.error(this, e.getMessage());
      }
   }//GEN-LAST:event_btnProcesarActionPerformed

   private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      this.dispose();
   }//GEN-LAST:event_btnSalirActionPerformed

   private void cboOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboOrigenActionPerformed
      int index = cboOrigen.getSelectedIndex();
      if (index == -1) {
         return;
      }
      ComboModel model = (ComboModel) cboOrigen.getSelectedItem();
      UtilView.llenarCombo(cboDestino, consultaController.leerCiudades(model.getId()));
      establecerNombre();
   }//GEN-LAST:event_cboOrigenActionPerformed

   private void cboDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDestinoActionPerformed
      establecerNombre();
   }//GEN-LAST:event_cboDestinoActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnProcesar;
   private javax.swing.JButton btnSalir;
   private javax.swing.JComboBox<ComboModel> cboDestino;
   private javax.swing.JComboBox<ComboModel> cboOrigen;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JTextField txtDuracion;
   private javax.swing.JTextField txtNombre;
   private javax.swing.JTextField txtPrecio1;
   private javax.swing.JTextField txtPrecio2;
   private javax.swing.JTextField txtPrecio3;
   // End of variables declaration//GEN-END:variables

   
   private void establecerNombre(){
      // Origen
      ComboModel origen = new ComboModel(0, "NONE");
      if(cboOrigen.getSelectedIndex()!=-1){
         origen = (ComboModel) cboOrigen.getSelectedItem();
      }
      // Destino
      ComboModel destino = new ComboModel(0, "NONE");
      if(cboDestino.getSelectedIndex()!=-1){
         destino = (ComboModel) cboDestino.getSelectedItem();
      }
      // Nombre
      String nombre = origen.getEtiqueta().toUpperCase() + " - " + destino.getEtiqueta().toUpperCase();
      txtNombre.setText(nombre);
   }
   
}
