/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package pe.edu.uni.educaapp.view;

import javax.swing.JInternalFrame;
import pe.edu.uni.educaapp.dto.EmpleadoDto;
import pe.edu.uni.educaapp.util.Session;

/**
 *
 * @author Gustavo Coronel
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        establecerTitulo();
    }

    private void establecerTitulo() {
        EmpleadoDto usuario = (EmpleadoDto) Session.get("USUARIO");
        String titulo = "Educa App (Usuario:" + usuario.getUsuario() + ")";
        this.setTitle(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        menuProcesosMatricula = new javax.swing.JMenuItem();
        menuTablas = new javax.swing.JMenu();
        menuTablasAlumnos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        menuProcesos.setText("Procesos");

        menuProcesosMatricula.setText("Matricula");
        menuProcesosMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesosMatriculaActionPerformed(evt);
            }
        });
        menuProcesos.add(menuProcesosMatricula);

        menuBar.add(menuProcesos);

        menuTablas.setText("Tablas");

        menuTablasAlumnos.setText("Alumnos");
        menuTablasAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablasAlumnosActionPerformed(evt);
            }
        });
        menuTablas.add(menuTablasAlumnos);

        menuBar.add(menuTablas);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuProcesosMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosMatriculaActionPerformed
        mostrarForm(ProcMatriculaView.class);
    }//GEN-LAST:event_menuProcesosMatriculaActionPerformed

    private void menuTablasAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasAlumnosActionPerformed
        mostrarForm(MantAlumnosView.class);
    }//GEN-LAST:event_menuTablasAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenuItem menuProcesosMatricula;
    private javax.swing.JMenu menuTablas;
    private javax.swing.JMenuItem menuTablasAlumnos;
    // End of variables declaration//GEN-END:variables

    private void mostrarForm(Class<?> aClass) {
        try {
            // Variable de control
            JInternalFrame view = null;
            // Buscar instancia
            for (JInternalFrame form : desktopPane.getAllFrames()) {
                if (aClass.isInstance(form)) {
                    view = form;
                    break;
                }
            }
            // Crear instancia
            if (view == null) {
                //view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
                view = (JInternalFrame) aClass.getConstructor().newInstance();
                desktopPane.add(view);
                view.setVisible(true);
                view.setMaximum(true);
            }
            view.setSelected(true);
        } catch (Exception e) {
        }
    }

}
