ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

create user BANCOEUREKA identified by admin;

GRANT CONNECT, RESOURCE TO BANCOEUREKA;

ALTER USER BANCOEUREKA QUOTA UNLIMITED ON USERS;

GRANT CREATE VIEW TO BANCOEUREKA; 


