package pe.ld.ventas.layer.view;

import java.awt.Image;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRMapCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import pe.ld.ventas.entity.Empleado;
import pe.ld.ventas.layer.dao.database.AccesoDB;
import pe.ld.ventas.layer.model.ReporteModel;
import pe.ld.ventas.util.ReportViewInternal;
import pe.ld.ventas.util.Session;

public class MainView extends javax.swing.JFrame {

    public MainView() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        agregarVistas();
        establecerTitulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        mnuTablas = new javax.swing.JMenu();
        mnuTablasCatalogo = new javax.swing.JMenuItem();
        mnuProcesos = new javax.swing.JMenu();
        mnuProcesosVenta = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mnuRepoCatalogo = new javax.swing.JMenuItem();
        mnuRepoEmpleados = new javax.swing.JMenuItem();
        mnuRepoEmpleados2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("V E N T A S");

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        mnuTablas.setText("Tablas");

        mnuTablasCatalogo.setText("Catalogo");
        mnuTablasCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTablasCatalogoActionPerformed(evt);
            }
        });
        mnuTablas.add(mnuTablasCatalogo);

        menuBar.add(mnuTablas);

        mnuProcesos.setText("Procesos");

        mnuProcesosVenta.setText("Venta");
        mnuProcesosVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProcesosVentaActionPerformed(evt);
            }
        });
        mnuProcesos.add(mnuProcesosVenta);

        menuBar.add(mnuProcesos);

        mnuReportes.setText("Reportes");

        mnuRepoCatalogo.setText("Catalogo");
        mnuRepoCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepoCatalogoActionPerformed(evt);
            }
        });
        mnuReportes.add(mnuRepoCatalogo);

        mnuRepoEmpleados.setText("Empleados");
        mnuRepoEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepoEmpleadosActionPerformed(evt);
            }
        });
        mnuReportes.add(mnuRepoEmpleados);

        mnuRepoEmpleados2.setText("Empleados 2");
        mnuRepoEmpleados2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepoEmpleados2ActionPerformed(evt);
            }
        });
        mnuReportes.add(mnuRepoEmpleados2);

        menuBar.add(mnuReportes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

	private void mnuTablasCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTablasCatalogoActionPerformed
            mostrar(MantCatalogoView.getInstancia());
	}//GEN-LAST:event_mnuTablasCatalogoActionPerformed

	private void mnuProcesosVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProcesosVentaActionPerformed
            mostrar(VentaView.getInstancia());
	}//GEN-LAST:event_mnuProcesosVentaActionPerformed

	private void mnuRepoCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepoCatalogoActionPerformed
            try {

                // Usando el archivo JRXML y el objeto Connection
                Connection cn = AccesoDB.getConnection();
                Map pars = new HashMap();
                InputStream is = getClass().getResourceAsStream("reports/repoCatalogo.jrxml");
                JasperReport rep = JasperCompileManager.compileReport(is);
                JasperPrint print = JasperFillManager.fillReport(rep, pars, cn);

                // Visualizando el Reporte
                // JasperViewer viewer = new JasperViewer(print, false);
                // viewer.setTitle("CATALOGO");
                // viewer.setVisible(true);
                ReportViewInternal rvi = new ReportViewInternal("CATALOGO");
                rvi.setReporte(print);
                rvi.restoreTitleBar();
                desktopPane.add(rvi);
                rvi.setVisible(true);

                try {
                    cn.close();
                } catch (Exception e) {
                }

                //JasperViewer.viewReport(print);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRORE", JOptionPane.ERROR_MESSAGE);
            }

	}//GEN-LAST:event_mnuRepoCatalogoActionPerformed

    private void mnuRepoEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepoEmpleadosActionPerformed
        try {
            // Datos
            Connection cn = AccesoDB.getConnection();
            // Usando el archivo JRXML y el objeto Connection
            Map pars = new HashMap();
            InputStream is = getClass().getResourceAsStream("reports/repoEmpleados.jrxml");
            JasperReport rep = JasperCompileManager.compileReport(is);
            JasperPrint print = JasperFillManager.fillReport(rep, pars, cn);

            // Visualizando el Reporte
            JasperViewer viewer = new JasperViewer(print, false);
            viewer.setTitle("REPORTE DE EMPLEADOS");
            viewer.setVisible(true);

            try {
                cn.close();
            } catch (Exception e) {
            }

            //JasperViewer.viewReport(print);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRORE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnuRepoEmpleadosActionPerformed

    private void mnuRepoEmpleados2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepoEmpleados2ActionPerformed

        try {
            // Datos
            ReporteModel reporteModel = new ReporteModel();
            List<Map<String, ?>> lista = reporteModel.traerEmpleados();
            JRMapCollectionDataSource data = new JRMapCollectionDataSource(lista);
            // Usando el archivo JRXML y el objeto Connection
            Connection cn = AccesoDB.getConnection();
            Map pars = new HashMap();
            InputStream is = getClass().getResourceAsStream("reports/repoEmpleados.jrxml");
            JasperReport rep = JasperCompileManager.compileReport(is);
            JasperPrint print = JasperFillManager.fillReport(rep, pars, data);
            // Visualizando el Reporte
            ReportViewInternal rvi = new ReportViewInternal("EMPLEADOS");
            rvi.setReporte(print);
            rvi.restoreTitleBar();
            desktopPane.add(rvi);
            rvi.setVisible(true);

            try {
                cn.close();
            } catch (Exception e) {
            }

            //JasperViewer.viewReport(print);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRORE", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_mnuRepoEmpleados2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
		 * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
		 * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuProcesos;
    private javax.swing.JMenuItem mnuProcesosVenta;
    private javax.swing.JMenuItem mnuRepoCatalogo;
    private javax.swing.JMenuItem mnuRepoEmpleados;
    private javax.swing.JMenuItem mnuRepoEmpleados2;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenu mnuTablas;
    private javax.swing.JMenuItem mnuTablasCatalogo;
    // End of variables declaration//GEN-END:variables

    /**
     * Este método se encarga de agregar todos los JInternalFrame al panel
     * (destopPane).
     */
    private void agregarVistas() {
        desktopPane.add(MantCatalogoView.getInstancia());
        desktopPane.add(VentaView.getInstancia());
    }

    private void mostrar(javax.swing.JInternalFrame instancia) {
        instancia.setVisible(true);
        instancia.setEnabled(true);
    }

    private void establecerTitulo() {
        String titulo = "..:: V E N T A S ::..";
        Empleado o = (Empleado) Session.get("empleado");
        titulo += " [ USUARIO: " + o.getUsuario() + " ]";
        this.setTitle(titulo);
        Image icon = new ImageIcon(getClass().getResource("/pe/ld/ventas/img/logo.jpg")).getImage();
        setIconImage(icon);
    }
}
